name: Automate State Transitions CI

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildPlatform: 'Any CPU'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.300'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'src'
    feedsToUse: 'select'

- task: VSBuild@1
  inputs:
    solution: 'src/*.sln'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: 'Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src'
    arguments: '--configuration Release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'