name: Automate State Transitions CI

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.300'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'src'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src'
    arguments: '--configuration Release'
